name: file_content_aggregator
description: A Flutter application to aggregate content from text files in a directory.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Убедитесь, что версия SDK соответствует

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9 # Для управления состоянием
  file_picker: ^6.1.1     # Для выбора директории
  path: ^1.8.3            # Для работы с путями
  shared_preferences: ^2.2.2 # Для сохранения настроек
  clipboard: ^0.1.3       # Для копирования в буфер обмена
  material_design_icons_flutter: ^7.0.7296 # Для дополнительных иконок (если понадобятся, стандартных Material много)
  
  # Используйте flutter_lints для анализа кода
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic